### ISSUE TITLE
A function cannot be hooked two times in the same process without causing a crash

### ISSUE THREAD

**Issue by andrewwiik** [comex/substitute#25] opened 2018-02-17 03:33 UTC
When I have two different tweaks that both hook MGGetBoolAnswer using the following code (just different keys) it crashes SpringBoard:

```objc
extern "C" BOOL MGGetBoolAnswer(CFStringRef);
%hookf(BOOL, MGGetBoolAnswer, CFStringRef key)
{
    #define k(key_) CFEqual(key, CFSTR(key_))
    if (k("eQd5mlz0BN0amTp/2ccMoA")
        || k("n/aVhqpGjESEbIjvJbEHKg") 
        || k("+fgL2ovGydvB5CWd1JI1qg"))
        return isEnabled;
    return %orig;
}
```

**Correction:** Any two tweaks that hook the same function in the same process will cause that process to crash.

**Other Example**
```objc
static BOOL (*old__IS_D2x)();
static BOOL isActualIPhoneX = NO;
BOOL _IS_D2x(){
    if (!isActualIPhoneX) {
        isActualIPhoneX = old__IS_D2x();
        isActualIPhoneX = NO;
    }
    return YES;
}

%ctor {
    // _IS_D2x is a iOS 11.1+ Specific Function to determine if the phone is an X and it is in the UIKit framework
    MSHookFunction(((void*)MSFindSymbol(NULL, "_IS_D2x")),(void*)_IS_D2x, (void**)&old__IS_D2x);
}
```

**Note:** I am not that experienced with lldb and gdb but you could pick any function on iOS 11 and cause this crash by hooking the function two times and for each hook give a different implementation, the implementations each having a case where they would return the original value of the original function before it was hooked, or in the case of the second hook the implementation from the first.

--------
  * iOS version: 11.1.2
  * iDevice model: iPhone 6
  * electra version: RC1

**Comment by stek29** [comment] 2018-02-17 03:51
Wait, it happens when you hook function twice or if you hook it twice & try to call originals in new ones?

**Comment by rweichler** [comment] 2018-02-17 05:20
oh wow..... yeah, i can verify this. tested in mediaserverd and the same thing.

```c
void (*orig1)();
void hook1() {
    return orig1();
}

void (*orig2)();
void hook2() {
    return orig1();
}

MSInitialize {
    MSHookFunction(some_function, (void *)&hook1, (void **)&orig1);
    MSHookFunction(some_function, (void *)&hook2, (void **)&orig2);
}
```

this is a complete showstopper :/

**Comment by andrewwiik** [comment] 2018-02-17 05:44
Okay so let's say I have to tweaks named "LittleX" and "Peek-a-Boo", and they are both hooking a function called "_IS_D2x". LittleX's hooks get loaded first, and that is totally fine, then Peek-A-Boos hooks gets loaded, then when trying to call the original function for peek-a-boo the program crashes, here are the address of all the functions at runtime right before the crash:

#### LittleX

```objc
BOOL _IS_D2x(){
	if (!isActualIPhoneX) {
		 NSLog(@"OLD X LittleX: %p", old__IS_D2x); // 0x101190000
                  NSLog(@"CURRENT X LittleX: %p", _IS_D2x); // 0x101107788
		isActualIPhoneX = old__IS_D2x();
	}
	if (!wantsStatusBar) return YES;
	return YES;
}
```

#### Peek-a-Boo

```objc
BOOL _IS_D2x(){
    if (!isActualIPhoneX) {
        NSLog(@"OLD X PEEK-A-BOO: %p", old__IS_D2x);  // 0x100e8c000
        NSLog(@"CURRENT X PEEK-A-BOO: %p", _IS_D2x); // 0x1011a329c
        isActualIPhoneX = NO;
    }
    return YES;
}
```

**Comment by comex** [comment] 2018-02-17 06:00
any chance you can get me the disassembly I asked for?

This is supposed to work.  There is no special handling for multiple hooking, but the combination of transform_dis and, on arm64, arm64_get_unwritten_temp_reg should handle relocating even unusual instructions at the start of the function, such as those left by a previous hook,

**Comment by andrewwiik** [comment] 2018-02-17 06:12
I am currently trying to do that

**Comment by andrewwiik** [comment] 2018-02-17 06:33
Okay so let's say I have to tweaks named "LittleX" and "Peek-a-Boo", and they are both hooking a function called "_IS_D2x". LittleX's hooks get loaded first, and that is totally fine, then Peek-A-Boos hooks gets loaded, then when trying to call the original function for peek-a-boo the program crashes, here are the address of all the functions at runtime right before the crash:

#### LittleX

```objc
BOOL _IS_D2x(){
	if (!isActualIPhoneX) {
	        NSLog(@"OLD X LittleX: %p", old__IS_D2x); // 0x101190000
                NSLog(@"CURRENT X LittleX: %p", _IS_D2x); // 0x101107788
		isActualIPhoneX = old__IS_D2x();
	}
	if (!wantsStatusBar) return YES;
	return YES;
}
```

#### Peek-a-Boo

```objc
BOOL _IS_D2x(){
    if (!isActualIPhoneX) {
        NSLog(@"OLD X PEEK-A-BOO: %p", old__IS_D2x);  // 0x100e8c000
        NSLog(@"CURRENT X PEEK-A-BOO: %p", _IS_D2x); // 0x1011a329c
        isActualIPhoneX = NO;
    }
    return YES;
}
```
### The Hooking Code 

#### LittleX

```objc
static BOOL (*old__IS_D2x)();

BOOL _IS_D2x(){
	if (!isActualIPhoneX) {
		NSLog(@"OLD X LittleX: %p", old__IS_D2x); // This Logged: 0x1016a4000
                 NSLog(@"CURRENT X LittleX: %p", _IS_D2x); // This Logged: 0x101607964
		isActualIPhoneX = old__IS_D2x();
	}
	if (!wantsStatusBar) return YES;
	return YES;
}

%ctor {
		struct substitute_function_hook hook = {((void*)MSFindSymbol(NULL, "_IS_D2x")), (void*)_IS_D2x, (void**)&old__IS_D2x};
	    int ret = substitute_hook_functions(&hook, 1, NULL, 1);
}

#### Peek-a-Boo
```objc
static BOOL (*old__IS_D2x)();
static BOOL isActualIPhoneX = NO;
BOOL _IS_D2x(){
    if (!isActualIPhoneX) {
        NSLog(@"OLD X PEEK-A-BOO: %p", old__IS_D2x); // This Logged: 0x101404000
        NSLog(@"CURRENT X PEEK-A-BOO: %p", _IS_D2x); // This Logged: 0x1016b761c
        isActualIPhoneX = NO;
    }
    return YES;
}

%ctor {
    struct substitute_function_hook hook = {((void*)MSFindSymbol(NULL, "_IS_D2x")), (void*)_IS_D2x, (void**)&old__IS_D2x};
    int ret = substitute_hook_functions(&hook, 1, NULL, 1);
}
```

### Disassembly of the 4 functions after all hooks are applied

#### LittleX's Original _IS_D2x Function (dis -s 0x1016a4000 -e 0x1016A4200)

```asm
0x1016a4000: mov    x8, #0x608
    0x1016a4004: movk   x8, #0xb6d4, lsl #16
    0x1016a4008: movk   x8, #0x1, lsl #32
    0x1016a400c: ldr    x8, [x8, #0x168]
    0x1016a4010: cmn    x8, #0x1                  ; =0x1 
    0x1016a4014: adrp   x18, 582672
    0x1016a4018: add    x18, x18, #0x614          ; =0x614 
    0x1016a401c: br     x18
    0x1016a4020: .long  0x00000000                ; unknown opcode
    0x1016a4024: .long  0x00000000                ; unknown opcode
    0x1016a4028: .long  0x00000000                ; unknown opcode
    0x1016a402c: .long  0x00000000                ; unknown opcode
    0x1016a4030: .long  0x00000000                ; unknown opcode
    0x1016a4034: .long  0x00000000                ; unknown opcode
    0x1016a4038: .long  0x00000000                ; unknown opcode
    0x1016a403c: .long  0x00000000                ; unknown opcode
    0x1016a4040: .long  0x00000000                ; unknown opcode
    0x1016a4044: .long  0x00000000                ; unknown opcode
    0x1016a4048: .long  0x00000000                ; unknown opcode
    0x1016a404c: .long  0x00000000                ; unknown opcode
    0x1016a4050: .long  0x00000000                ; unknown opcode
    0x1016a4054: .long  0x00000000                ; unknown opcode
    0x1016a4058: .long  0x00000000                ; unknown opcode
    0x1016a405c: .long  0x00000000                ; unknown opcode
    0x1016a4060: .long  0x00000000                ; unknown opcode
    0x1016a4064: .long  0x00000000                ; unknown opcode
    0x1016a4068: .long  0x00000000                ; unknown opcode
    0x1016a406c: .long  0x00000000                ; unknown opcode
    0x1016a4070: .long  0x00000000                ; unknown opcode
    0x1016a4074: .long  0x00000000                ; unknown opcode
    0x1016a4078: .long  0x00000000                ; unknown opcode
    0x1016a407c: .long  0x00000000                ; unknown opcode
    0x1016a4080: .long  0x00000000                ; unknown opcode
    0x1016a4084: .long  0x00000000                ; unknown opcode
    0x1016a4088: .long  0x00000000                ; unknown opcode
    0x1016a408c: .long  0x00000000                ; unknown opcode
    0x1016a4090: .long  0x00000000                ; unknown opcode
    0x1016a4094: .long  0x00000000                ; unknown opcode
    0x1016a4098: .long  0x00000000                ; unknown opcode
    0x1016a409c: .long  0x00000000                ; unknown opcode
    0x1016a40a0: .long  0x00000000                ; unknown opcode
    0x1016a40a4: .long  0x00000000                ; unknown opcode
    0x1016a40a8: .long  0x00000000                ; unknown opcode
    0x1016a40ac: .long  0x00000000                ; unknown opcode
    0x1016a40b0: .long  0x00000000                ; unknown opcode
    0x1016a40b4: .long  0x00000000                ; unknown opcode
    0x1016a40b8: .long  0x00000000                ; unknown opcode
    0x1016a40bc: .long  0x00000000                ; unknown opcode
    0x1016a40c0: .long  0x00000000                ; unknown opcode
    0x1016a40c4: .long  0x00000000                ; unknown opcode
    0x1016a40c8: .long  0x00000000                ; unknown opcode
    0x1016a40cc: .long  0x00000000                ; unknown opcode
    0x1016a40d0: .long  0x00000000                ; unknown opcode
    0x1016a40d4: .long  0x00000000                ; unknown opcode
    0x1016a40d8: .long  0x00000000                ; unknown opcode
    0x1016a40dc: .long  0x00000000                ; unknown opcode
    0x1016a40e0: .long  0x00000000                ; unknown opcode
    0x1016a40e4: .long  0x00000000                ; unknown opcode
    0x1016a40e8: .long  0x00000000                ; unknown opcode
    0x1016a40ec: .long  0x00000000                ; unknown opcode
    0x1016a40f0: .long  0x00000000                ; unknown opcode
    0x1016a40f4: .long  0x00000000                ; unknown opcode
    0x1016a40f8: .long  0x00000000                ; unknown opcode
    0x1016a40fc: .long  0x00000000                ; unknown opcode
    0x1016a4100: .long  0x00000000                ; unknown opcode
    0x1016a4104: .long  0x00000000                ; unknown opcode
    0x1016a4108: .long  0x00000000                ; unknown opcode
    0x1016a410c: .long  0x00000000                ; unknown opcode
    0x1016a4110: .long  0x00000000                ; unknown opcode
    0x1016a4114: .long  0x00000000                ; unknown opcode
    0x1016a4118: .long  0x00000000                ; unknown opcode
    0x1016a411c: .long  0x00000000                ; unknown opcode
    0x1016a4120: .long  0x00000000                ; unknown opcode
    0x1016a4124: .long  0x00000000                ; unknown opcode
    0x1016a4128: .long  0x00000000                ; unknown opcode
    0x1016a412c: .long  0x00000000                ; unknown opcode
    0x1016a4130: .long  0x00000000                ; unknown opcode
    0x1016a4134: .long  0x00000000                ; unknown opcode
    0x1016a4138: .long  0x00000000                ; unknown opcode
    0x1016a413c: .long  0x00000000                ; unknown opcode
    0x1016a4140: .long  0x00000000                ; unknown opcode
    0x1016a4144: .long  0x00000000                ; unknown opcode
    0x1016a4148: .long  0x00000000                ; unknown opcode
    0x1016a414c: .long  0x00000000                ; unknown opcode
    0x1016a4150: .long  0x00000000                ; unknown opcode
    0x1016a4154: .long  0x00000000                ; unknown opcode
    0x1016a4158: .long  0x00000000                ; unknown opcode
    0x1016a415c: .long  0x00000000                ; unknown opcode
    0x1016a4160: .long  0x00000000                ; unknown opcode
    0x1016a4164: .long  0x00000000                ; unknown opcode
    0x1016a4168: .long  0x00000000                ; unknown opcode
    0x1016a416c: .long  0x00000000                ; unknown opcode
    0x1016a4170: .long  0x00000000                ; unknown opcode
    0x1016a4174: .long  0x00000000                ; unknown opcode
    0x1016a4178: .long  0x00000000                ; unknown opcode
    0x1016a417c: .long  0x00000000                ; unknown opcode
    0x1016a4180: .long  0x00000000                ; unknown opcode
    0x1016a4184: .long  0x00000000                ; unknown opcode
    0x1016a4188: .long  0x00000000                ; unknown opcode
    0x1016a418c: .long  0x00000000                ; unknown opcode
    0x1016a4190: .long  0x00000000                ; unknown opcode
    0x1016a4194: .long  0x00000000                ; unknown opcode
    0x1016a4198: .long  0x00000000                ; unknown opcode
    0x1016a419c: .long  0x00000000                ; unknown opcode
    0x1016a41a0: .long  0x00000000                ; unknown opcode
    0x1016a41a4: .long  0x00000000                ; unknown opcode
    0x1016a41a8: .long  0x00000000                ; unknown opcode
    0x1016a41ac: .long  0x00000000                ; unknown opcode
    0x1016a41b0: .long  0x00000000                ; unknown opcode
    0x1016a41b4: .long  0x00000000                ; unknown opcode
    0x1016a41b8: .long  0x00000000                ; unknown opcode
    0x1016a41bc: .long  0x00000000                ; unknown opcode
    0x1016a41c0: .long  0x00000000                ; unknown opcode
    0x1016a41c4: .long  0x00000000                ; unknown opcode
    0x1016a41c8: .long  0x00000000                ; unknown opcode
    0x1016a41cc: .long  0x00000000                ; unknown opcode
    0x1016a41d0: .long  0x00000000                ; unknown opcode
    0x1016a41d4: .long  0x00000000                ; unknown opcode
    0x1016a41d8: .long  0x00000000                ; unknown opcode
    0x1016a41dc: .long  0x00000000                ; unknown opcode
    0x1016a41e0: .long  0x00000000                ; unknown opcode
    0x1016a41e4: .long  0x00000000                ; unknown opcode
    0x1016a41e8: .long  0x00000000                ; unknown opcode
    0x1016a41ec: .long  0x00000000                ; unknown opcode
    0x1016a41f0: .long  0x00000000                ; unknown opcode
    0x1016a41f4: .long  0x00000000                ; unknown opcode
    0x1016a41f8: .long  0x00000000                ; unknown opcode
    0x1016a41fc: .long  0x00000000                ; unknown opcode
```

#### LittleX's new _IS_D2x function (dis -a 0x101607964)

```asm
    0x101607964 <+0>:   sub    sp, sp, #0x20             ; =0x20 
    0x101607968 <+4>:   stp    x29, x30, [sp, #0x10]
    0x10160796c <+8>:   add    x29, sp, #0x10            ; =0x10 
    0x101607970 <+12>:  adrp   x8, 13
    0x101607974 <+16>:  add    x8, x8, #0x9e9            ; =0x9e9 
    0x101607978 <+20>:  ldrb   w9, [x8]
    0x10160797c <+24>:  tbnz   w9, #0x0, 0x1016079dc     ; <+120> at Tweak.xm
    0x101607980 <+28>:  adrp   x8, 13
    0x101607984 <+32>:  add    x8, x8, #0x9f0            ; =0x9f0 
    0x101607988 <+36>:  ldr    x8, [x8]
    0x10160798c <+40>:  mov    x9, sp
    0x101607990 <+44>:  str    x8, [x9]
    0x101607994 <+48>:  adrp   x0, 13
    0x101607998 <+52>:  add    x0, x0, #0x120            ; =0x120 
    0x10160799c <+56>:  bl     0x10161157c               ; symbol stub for: NSLog
    0x1016079a0 <+60>:  adrp   x8, 0
    0x1016079a4 <+64>:  add    x8, x8, #0x964            ; =0x964 
    0x1016079a8 <+68>:  mov    x9, sp
    0x1016079ac <+72>:  str    x8, [x9]
    0x1016079b0 <+76>:  adrp   x0, 13
    0x1016079b4 <+80>:  add    x0, x0, #0x140            ; =0x140 
    0x1016079b8 <+84>:  bl     0x10161157c               ; symbol stub for: NSLog
    0x1016079bc <+88>:  adrp   x8, 13
    0x1016079c0 <+92>:  add    x8, x8, #0x9f0            ; =0x9f0 
    0x1016079c4 <+96>:  ldr    x8, [x8]
    0x1016079c8 <+100>: blr    x8
    0x1016079cc <+104>: adrp   x8, 13
    0x1016079d0 <+108>: add    x8, x8, #0x9e9            ; =0x9e9 
    0x1016079d4 <+112>: and    w0, w0, #0x1
    0x1016079d8 <+116>: strb   w0, [x8]
    0x1016079dc <+120>: adrp   x8, 13
    0x1016079e0 <+124>: add    x8, x8, #0x9c0            ; =0x9c0 
    0x1016079e4 <+128>: ldrb   w9, [x8]
    0x1016079e8 <+132>: tbnz   w9, #0x0, 0x1016079fc     ; <+152> at Tweak.xm
    0x1016079ec <+136>: orr    w8, wzr, #0x1
    0x1016079f0 <+140>: and    w8, w8, #0x1
    0x1016079f4 <+144>: sturb  w8, [x29, #-0x1]
    0x1016079f8 <+148>: b      0x101607a08               ; <+164> at Tweak.xm:614
    0x1016079fc <+152>: orr    w8, wzr, #0x1
    0x101607a00 <+156>: and    w8, w8, #0x1
    0x101607a04 <+160>: sturb  w8, [x29, #-0x1]
    0x101607a08 <+164>: ldurb  w8, [x29, #-0x1]
    0x101607a0c <+168>: and    w8, w8, #0x1
    0x101607a10 <+172>: and    w0, w8, #0x1
    0x101607a14 <+176>: ldp    x29, x30, [sp, #0x10]
    0x101607a18 <+180>: add    sp, sp, #0x20             ; =0x20 
    0x101607a1c <+184>: ret  
```

#### Peek-a-Boo's original _IS_D2x (dis -s 0x101404000 -e 0x101404200)

```asm
    0x101404000: mov    x18, #0x7608
    0x101404004: movk   x18, #0x160, lsl #16
    0x101404008: movk   x18, #0x2, lsl #32
    0x10140400c: add    x18, x18, #0x964          ; =0x964 
    0x101404010: br     x18
    0x101404014: adrp   x17, 583344
    0x101404018: add    x17, x17, #0x614          ; =0x614 
    0x10140401c: br     x17
    0x101404020: .long  0x00000000                ; unknown opcode
    0x101404024: .long  0x00000000                ; unknown opcode
    0x101404028: .long  0x00000000                ; unknown opcode
    0x10140402c: .long  0x00000000                ; unknown opcode
    0x101404030: .long  0x00000000                ; unknown opcode
    0x101404034: .long  0x00000000                ; unknown opcode
    0x101404038: .long  0x00000000                ; unknown opcode
    0x10140403c: .long  0x00000000                ; unknown opcode
    0x101404040: .long  0x00000000                ; unknown opcode
    0x101404044: .long  0x00000000                ; unknown opcode
    0x101404048: .long  0x00000000                ; unknown opcode
    0x10140404c: .long  0x00000000                ; unknown opcode
    0x101404050: .long  0x00000000                ; unknown opcode
    0x101404054: .long  0x00000000                ; unknown opcode
    0x101404058: .long  0x00000000                ; unknown opcode
    0x10140405c: .long  0x00000000                ; unknown opcode
    0x101404060: .long  0x00000000                ; unknown opcode
    0x101404064: .long  0x00000000                ; unknown opcode
    0x101404068: .long  0x00000000                ; unknown opcode
    0x10140406c: .long  0x00000000                ; unknown opcode
    0x101404070: .long  0x00000000                ; unknown opcode
    0x101404074: .long  0x00000000                ; unknown opcode
    0x101404078: .long  0x00000000                ; unknown opcode
    0x10140407c: .long  0x00000000                ; unknown opcode
    0x101404080: .long  0x00000000                ; unknown opcode
    0x101404084: .long  0x00000000                ; unknown opcode
    0x101404088: .long  0x00000000                ; unknown opcode
    0x10140408c: .long  0x00000000                ; unknown opcode
    0x101404090: .long  0x00000000                ; unknown opcode
    0x101404094: .long  0x00000000                ; unknown opcode
    0x101404098: .long  0x00000000                ; unknown opcode
    0x10140409c: .long  0x00000000                ; unknown opcode
    0x1014040a0: .long  0x00000000                ; unknown opcode
    0x1014040a4: .long  0x00000000                ; unknown opcode
    0x1014040a8: .long  0x00000000                ; unknown opcode
    0x1014040ac: .long  0x00000000                ; unknown opcode
    0x1014040b0: .long  0x00000000                ; unknown opcode
    0x1014040b4: .long  0x00000000                ; unknown opcode
    0x1014040b8: .long  0x00000000                ; unknown opcode
    0x1014040bc: .long  0x00000000                ; unknown opcode
    0x1014040c0: .long  0x00000000                ; unknown opcode
    0x1014040c4: .long  0x00000000                ; unknown opcode
    0x1014040c8: .long  0x00000000                ; unknown opcode
    0x1014040cc: .long  0x00000000                ; unknown opcode
    0x1014040d0: .long  0x00000000                ; unknown opcode
    0x1014040d4: .long  0x00000000                ; unknown opcode
    0x1014040d8: .long  0x00000000                ; unknown opcode
    0x1014040dc: .long  0x00000000                ; unknown opcode
    0x1014040e0: .long  0x00000000                ; unknown opcode
    0x1014040e4: .long  0x00000000                ; unknown opcode
    0x1014040e8: .long  0x00000000                ; unknown opcode
    0x1014040ec: .long  0x00000000                ; unknown opcode
    0x1014040f0: .long  0x00000000                ; unknown opcode
    0x1014040f4: .long  0x00000000                ; unknown opcode
    0x1014040f8: .long  0x00000000                ; unknown opcode
    0x1014040fc: .long  0x00000000                ; unknown opcode
    0x101404100: .long  0x00000000                ; unknown opcode
    0x101404104: .long  0x00000000                ; unknown opcode
    0x101404108: .long  0x00000000                ; unknown opcode
    0x10140410c: .long  0x00000000                ; unknown opcode
    0x101404110: .long  0x00000000                ; unknown opcode
    0x101404114: .long  0x00000000                ; unknown opcode
    0x101404118: .long  0x00000000                ; unknown opcode
    0x10140411c: .long  0x00000000                ; unknown opcode
    0x101404120: .long  0x00000000                ; unknown opcode
    0x101404124: .long  0x00000000                ; unknown opcode
    0x101404128: .long  0x00000000                ; unknown opcode
    0x10140412c: .long  0x00000000                ; unknown opcode
    0x101404130: .long  0x00000000                ; unknown opcode
    0x101404134: .long  0x00000000                ; unknown opcode
    0x101404138: .long  0x00000000                ; unknown opcode
    0x10140413c: .long  0x00000000                ; unknown opcode
    0x101404140: .long  0x00000000                ; unknown opcode
    0x101404144: .long  0x00000000                ; unknown opcode
    0x101404148: .long  0x00000000                ; unknown opcode
    0x10140414c: .long  0x00000000                ; unknown opcode
    0x101404150: .long  0x00000000                ; unknown opcode
    0x101404154: .long  0x00000000                ; unknown opcode
    0x101404158: .long  0x00000000                ; unknown opcode
    0x10140415c: .long  0x00000000                ; unknown opcode
    0x101404160: .long  0x00000000                ; unknown opcode
    0x101404164: .long  0x00000000                ; unknown opcode
    0x101404168: .long  0x00000000                ; unknown opcode
    0x10140416c: .long  0x00000000                ; unknown opcode
    0x101404170: .long  0x00000000                ; unknown opcode
    0x101404174: .long  0x00000000                ; unknown opcode
    0x101404178: .long  0x00000000                ; unknown opcode
    0x10140417c: .long  0x00000000                ; unknown opcode
    0x101404180: .long  0x00000000                ; unknown opcode
    0x101404184: .long  0x00000000                ; unknown opcode
    0x101404188: .long  0x00000000                ; unknown opcode
    0x10140418c: .long  0x00000000                ; unknown opcode
    0x101404190: .long  0x00000000                ; unknown opcode
    0x101404194: .long  0x00000000                ; unknown opcode
    0x101404198: .long  0x00000000                ; unknown opcode
    0x10140419c: .long  0x00000000                ; unknown opcode
    0x1014041a0: .long  0x00000000                ; unknown opcode
    0x1014041a4: .long  0x00000000                ; unknown opcode
    0x1014041a8: .long  0x00000000                ; unknown opcode
    0x1014041ac: .long  0x00000000                ; unknown opcode
    0x1014041b0: .long  0x00000000                ; unknown opcode
    0x1014041b4: .long  0x00000000                ; unknown opcode
    0x1014041b8: .long  0x00000000                ; unknown opcode
    0x1014041bc: .long  0x00000000                ; unknown opcode
    0x1014041c0: .long  0x00000000                ; unknown opcode
    0x1014041c4: .long  0x00000000                ; unknown opcode
    0x1014041c8: .long  0x00000000                ; unknown opcode
    0x1014041cc: .long  0x00000000                ; unknown opcode
    0x1014041d0: .long  0x00000000                ; unknown opcode
    0x1014041d4: .long  0x00000000                ; unknown opcode
    0x1014041d8: .long  0x00000000                ; unknown opcode
    0x1014041dc: .long  0x00000000                ; unknown opcode
    0x1014041e0: .long  0x00000000                ; unknown opcode
    0x1014041e4: .long  0x00000000                ; unknown opcode
    0x1014041e8: .long  0x00000000                ; unknown opcode
    0x1014041ec: .long  0x00000000                ; unknown opcode
    0x1014041f0: .long  0x00000000                ; unknown opcode
    0x1014041f4: .long  0x00000000                ; unknown opcode
    0x1014041f8: .long  0x00000000                ; unknown opcode
    0x1014041fc: .long  0x00000000                ; unknown opcode
```

#### Peek-a-Boo's new _IS_D2X function (dis -a 0x1016b761c)

```asm
PeekaBoo.dylib`_IS_D2x:
    0x1016b761c <+0>:   sub    sp, sp, #0x20             ; =0x20 
    0x1016b7620 <+4>:   stp    x29, x30, [sp, #0x10]
    0x1016b7624 <+8>:   add    x29, sp, #0x10            ; =0x10 
    0x1016b7628 <+12>:  adrp   x8, 5
    0x1016b762c <+16>:  add    x8, x8, #0x613            ; =0x613 
    0x1016b7630 <+20>:  ldrb   w9, [x8]
    0x1016b7634 <+24>:  tbnz   w9, #0x0, 0x1016b7680     ; <+100> at Alt.xm
    0x1016b7638 <+28>:  adrp   x8, 5
    0x1016b763c <+32>:  add    x8, x8, #0x618            ; =0x618 
    0x1016b7640 <+36>:  ldr    x8, [x8]
    0x1016b7644 <+40>:  mov    x9, sp
    0x1016b7648 <+44>:  str    x8, [x9]
    0x1016b764c <+48>:  adrp   x0, 5
    0x1016b7650 <+52>:  add    x0, x0, #0x100            ; =0x100 
    0x1016b7654 <+56>:  bl     0x1016baa8c               ; symbol stub for: NSLog
    0x1016b7658 <+60>:  adrp   x8, 0
    0x1016b765c <+64>:  add    x8, x8, #0x61c            ; =0x61c 
    0x1016b7660 <+68>:  mov    x9, sp
    0x1016b7664 <+72>:  str    x8, [x9]
    0x1016b7668 <+76>:  adrp   x0, 5
    0x1016b766c <+80>:  add    x0, x0, #0x120            ; =0x120 
    0x1016b7670 <+84>:  bl     0x1016baa8c               ; symbol stub for: NSLog
    0x1016b7674 <+88>:  adrp   x8, 5
    0x1016b7678 <+92>:  add    x8, x8, #0x613            ; =0x613 
    0x1016b767c <+96>:  strb   wzr, [x8]
    0x1016b7680 <+100>: orr    w8, wzr, #0x1
    0x1016b7684 <+104>: and    w0, w8, #0x1
    0x1016b7688 <+108>: ldp    x29, x30, [sp, #0x10]
    0x1016b768c <+112>: add    sp, sp, #0x20             ; =0x20 
    0x1016b7690 <+116>: ret    
```

**Comment by andrewwiik** [comment] 2018-02-17 07:18
The other example seems sort of complicated so I have done tests with the example by @rweichler 

#### The Code (Exactly)

```objc
%config(generator=internal) // use default obj c code generation

struct substitute_function_hook {
	void *function;
	void *replacement;
	void *old_ptr;
	int options;
};

extern "C" int substitute_hook_functions(const struct substitute_function_hook *hooks, size_t nhooks, void **recordp, int options);

void (*orig1)();
void hook1() {
    printf("hook1 address: %p\n", &hook1); // Printed: 0x100d73ce0
    printf("orig1 address: %p\n", &orig1); // Printed: 0x100d74070
    return orig1();
}

void (*orig2)();
void hook2() {
    printf("hook2 address: %p\n", &hook2); // Printed: 0x100d73d4c
    printf("orig2 address: %p\n", &orig2); // Printed: 0x100d74078
    printf("hook2");
    return orig2();
}

void some_function() {
    printf("blah\n");
}

%ctor {
	struct substitute_function_hook shook1 = {(void*)&some_function, (void *)&hook1, (void *)&orig1};
	int ret1 = substitute_hook_functions(&shook1, 1, NULL, 1);
	printf("shook1 result: %d\n", ret1); // Printed: 0
	some_function();

	struct substitute_function_hook shook2 = {(void*)&some_function, (void *)&hook2, (void *)&orig2};
	int ret2 = substitute_hook_functions(&shook2, 1, NULL, 1);
	printf("shook2 result: %d\n", ret2); // Printed: 0
	some_function();
}
```

### Disassembly of functions using LLDB

#### orig1
```asm
```

**Comment by andrewwiik** [comment] 2018-02-17 07:18
Whoops didn't mean to close

**Comment by comex** [comment] 2018-02-17 09:48
Thank you!  I'm pretty sure I figured out what the problem is, and even though I'm not generally able to do proper maintenance on this project (sorry), I will fix this bug tomorrow.

Basically, this:
```
    0x101404000: mov    x18, #0x7608
    0x101404004: movk   x18, #0x160, lsl #16
    0x101404008: movk   x18, #0x2, lsl #32
```
was originally a single ADRP instruction, which sets a register to (current PC & ~0xfff) plus an immediate.  When relocating it in memory, substitute transforms it to the above sequence that hardcodes the address.  That's fine, but… I forgot the ~0xfff part (in lib/arm64/dis-main.h under `P(adrplabel_label_unk_Xd_1_ADRP)`), so it sets the wrong value.  And I never wrote a test for this because I'm an idiot.

**Comment by andrewwiik** [comment] 2018-02-17 09:52
Thanks @comex now I can go to sleep without nightmares

**Comment by comex** [comment] 2018-02-17 23:02
I pushed a fix.  Please merge it into the fork you're using and let me know if it works.

**Closed** 2018-03-03 23:30 UTC
